import numpy as np
import matplotlib.pyplot as plt
# import random
# import cv2
import pyautogui
import time
# import txt

def main():
    # first generate racing line here using
    # file generated by generatetrack.py
    xs, ys = [], []
    with open('track.txt', 'r') as f:
        for line in f:
            newline = line.split('=')
            xs.append(int(newline[1].split(',')[0]))
            ys.append(int(newline[-1][:-2]))
            
    print('xs: ' + str(xs))
    print('ys: ' + str(ys))
    # plt.plot(xs,ys)
    # plt.show()
    

if __name__ == "__main__":
    main()
